// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPacklist struct {
	Slug        string  `json:"slug"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type Token struct {
	Value string `json:"value"`
}
