// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
)

type NewPacklist struct {
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	User        primitive.ObjectID `json:"user"`
}

type Token struct {
	Value string `json:"value"`
}
